module.exports = [
    {
        "name": "Shakira",
        "career": "Musician",
        "birthYear": 1977,
        "careerStart": 1990,
        "usBreakout": 2001,
        "age": 37,
        "careerLength": 24,
        "netWorth2014": 200000000,
        "yearsUntilBreakout": 11,
        "bio": "http://en.wikipedia.org/wiki/Shakira",
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/singers/shakira-net-worth/"
    },
    {
        "name": "Usher",
        "career": "Musician",
        "birthYear": 1978,
        "careerStart": 1991,
        "usBreakout": 1997,
        "age": 36,
        "careerLength": 23,
        "netWorth2014": 110000000,
        "yearsUntilBreakout": 6,
        "bio": "http://en.wikipedia.org/wiki/Usher_(entertainer)",
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/richest-rappers/usher-net-worth/"
    },
    {
        "name": "Danielle Bradbery",
        "career": "Musician",
        "knownFrom": "The Voice Season 4 Winner",
        "birthYear": 1996,
        "careerStart": 2013,
        "usBreakout": 2013,
        "age": 18,
        "careerLength": 1,
        "netWorth2014": 300000,
        "yearsUntilBreakout": 0,
        "bio": "http://en.wikipedia.org/wiki/Danielle_Bradbery",
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/singers/danielle-bradbery-net-worth/"
    },
    {
        "name": "Cassadee Pope",
        "career": "Musician",
        "knownFrom": "The Voice Season 3 Winner",
        "birthYear": 1989,
        "careerStart": 2008,
        "usBreakout": 2012,
        "age": 25,
        "careerLength": 6,
        "netWorth2014": 4000000,
        "yearsUntilBreakout": 4,
        "bio": "http://en.wikipedia.org/wiki/Cassadee_Pope",
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/singers/cassadee-pope-net-worth/"
    },
    {
        "name": "Javier Colon",
        "career": "Musician",
        "knownFrom": "The Voice Season 1 Winner",
        "birthYear": 1978,
        "careerStart": 1999,
        "usBreakout": 2011,
        "age": 36,
        "careerLength": 15,
        "netWorth2014": 1800000,
        "yearsUntilBreakout": 12,
        "bio": "http://en.wikipedia.org/wiki/Javier_Colon",
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/singers/javier-colon-net-worth/"
    },
    {
        "name": "John Resig",
        "career": "Programmer",
        "knownFrom": "jQuery",
        "birthYear": 1984,
        "careerStart": 2006,
        "usBreakout": 2008,
        "age": 30,
        "careerLength": 8,
        "netWorth2014": 50000000,
        "yearsUntilBreakout": 2,
        "bio": "http://en.wikipedia.org/wiki/John_Resig",
        "netWorth": "http://www.celebritynetworth.com/richest-businessmen/business-executives/john-resig-net-worth/"
    },
    {
        "name": "Tim Ferriss",
        "career": "Entreprenuer",
        "knownFrom": "4-hour Work Week",
        "birthYear": 1977,
        "careerStart": 2001,
        "usBreakout": 2007,
        "age": 37,
        "careerLength": 13,
        "netWorth2014": 15000000,
        "yearsUntilBreakout": 6,
        "bio": "http://en.wikipedia.org/wiki/Timothy_Ferriss",
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/authors/tim-ferriss-net-worth/"
    },
    {
        "name": "Jimmy Wales",
        "career": "Entreprenuer",
        "knownFrom": "Wikipedia",
        "birthYear": 1966,
        "careerStart": 1995,
        "usBreakout": 2005,
        "age": 48,
        "careerLength": 19,
        "netWorth2014": 1000000,
        "yearsUntilBreakout": 10,
        "bio": "http://en.wikipedia.org/wiki/Jimmy_Wales",
        "netWorth": "http://www.celebritynetworth.com/richest-businessmen/ceos/jimmy-wales-net-worth/"
    },
    {
        "name": "Garrison Keillor",
        "career": "Radio",
        "knownFrom": "A Prairie Home Companion",
        "birthYear": 1942,
        "careerStart": 1970,
        "usBreakout": 1978,
        "age": 72,
        "careerLength": 44,
        "netWorth2014": 1500000,
        "yearsUntilBreakout": 8,
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/authors/garrison-keillor-net-worth/"
    },
    {
        "name": "Bill Clinton",
        "career": "Politician",
        "knownFrom": "US President",
        "birthYear": 1946,
        "careerStart": 1976,
        "usBreakout": 1992,
        "age": 68,
        "careerLength": 38,
        "netWorth2014": 80000000,
        "yearsUntilBreakout": 16,
        "netWorth": "http://www.celebritynetworth.com/richest-politicians/presidents/bill-clinton-net-worth/"
    },
    {
        "name": "Barak Obama",
        "career": "Politician",
        "knownFrom": "US President",
        "birthYear": 1961,
        "careerStart": 1992,
        "usBreakout": 2008,
        "age": 53,
        "careerLength": 22,
        "netWorth2014": 12200000,
        "yearsUntilBreakout": 16,
        "netWorth": "http://www.celebritynetworth.com/richest-politicians/presidents/barack-obama-net-worth/"
    },
    {
        "name": "Nancy Pelosi",
        "career": "Politician",
        "knownFrom": "US Representative",
        "birthYear": 1940,
        "careerStart": 1969,
        "usBreakout": 2007,
        "age": 74,
        "careerLength": 45,
        "netWorth2014": 100000000,
        "yearsUntilBreakout": 38,
        "netWorth": "http://www.celebritynetworth.com/richest-politicians/democrats/nancy-pelosi-net-worth/"
    },
    {
        "name": "Avg US Senator (2011)",
        "career": "Politician",
        "age": 62,
        "careerLength": 0,
        "netWorth2014": 14013596,
        "yearsUntilBreakout": 0,
        "bio": "http://www.slate.com/articles/news_and_politics/explainer/2013/01/average_age_of_members_of_u_s_congress_are_our_senators_and_representatives.html",
        "netWorth": "http://ballotpedia.org/Net_worth_of_United_States_Senators_and_Representatives"
    },
    {
        "name": "Avg US Representative (2011)",
        "career": "Politician",
        "age": 57,
        "careerLength": 0,
        "netWorth2014": 6594859,
        "yearsUntilBreakout": 0,
        "bio": "http://www.slate.com/articles/news_and_politics/explainer/2013/01/average_age_of_members_of_u_s_congress_are_our_senators_and_representatives.html",
        "netWorth": "http://ballotpedia.org/Net_worth_of_United_States_Senators_and_Representatives"
    },
    {
        "career": "Median US Citizen",
        "age": 30,
        "careerLength": 0,
        "netWorth2014": 8525,
        "yearsUntilBreakout": 0,
        "netWorth": "http://cgi.money.cnn.com/tools/networth_ageincome/"
    },
    {
        "career": "Median US Citizen",
        "age": 40,
        "careerLength": 0,
        "netWorth2014": 51575,
        "yearsUntilBreakout": 0,
        "netWorth": "http://cgi.money.cnn.com/tools/networth_ageincome/"
    },
    {
        "career": "Median US Citizen",
        "age": 50,
        "careerLength": 0,
        "netWorth2014": 98350,
        "yearsUntilBreakout": 0,
        "netWorth": "http://cgi.money.cnn.com/tools/networth_ageincome/"
    },
    {
        "career": "Median US Citizen",
        "age": 60,
        "careerLength": 0,
        "netWorth2014": 180125,
        "yearsUntilBreakout": 0,
        "netWorth": "http://cgi.money.cnn.com/tools/networth_ageincome/"
    },
    {
        "career": "Median US Citizen",
        "age": 75,
        "careerLength": 0,
        "netWorth2014": 232000,
        "yearsUntilBreakout": 0,
        "netWorth": "http://cgi.money.cnn.com/tools/networth_ageincome/"
    },
    {
        "career": "Above Avg US Citizen",
        "age": 65,
        "careerLength": 0,
        "netWorth2014": 2420500,
        "yearsUntilBreakout": 0,
        "netWorth": "http://www.financialsamurai.com/the-average-net-worth-for-the-above-average-person/"
    },
    {
        "career": "Above Avg US Citizen",
        "age": 60,
        "careerLength": 0,
        "netWorth2014": 1908500,
        "yearsUntilBreakout": 0,
        "netWorth": "http://www.financialsamurai.com/the-average-net-worth-for-the-above-average-person/"
    },
    {
        "career": "Above Avg US Citizen",
        "age": 55,
        "careerLength": 0,
        "netWorth2014": 1511500,
        "yearsUntilBreakout": 0,
        "netWorth": "http://www.financialsamurai.com/the-average-net-worth-for-the-above-average-person/"
    },
    {
        "career": "Above Avg US Citizen",
        "age": 50,
        "careerLength": 0,
        "netWorth2014": 1171500,
        "yearsUntilBreakout": 0,
        "netWorth": "http://www.financialsamurai.com/the-average-net-worth-for-the-above-average-person/"
    },
    {
        "career": "Above Avg US Citizen",
        "age": 45,
        "careerLength": 0,
        "netWorth2014": 891000,
        "yearsUntilBreakout": 0,
        "netWorth": "http://www.financialsamurai.com/the-average-net-worth-for-the-above-average-person/"
    },
    {
        "career": "Above Avg US Citizen",
        "age": 40,
        "careerLength": 0,
        "netWorth2014": 643000,
        "yearsUntilBreakout": 0,
        "netWorth": "http://www.financialsamurai.com/the-average-net-worth-for-the-above-average-person/"
    },
    {
        "career": "Above Avg US Citizen",
        "age": 35,
        "careerLength": 0,
        "netWorth2014": 418000,
        "yearsUntilBreakout": 0,
        "netWorth": "http://www.financialsamurai.com/the-average-net-worth-for-the-above-average-person/"
    },
    {
        "career": "Above Avg US Citizen",
        "age": 30,
        "careerLength": 0,
        "netWorth2014": 239000,
        "yearsUntilBreakout": 0,
        "netWorth": "http://www.financialsamurai.com/the-average-net-worth-for-the-above-average-person/"
    },
    {
        "career": "Above Avg US Citizen",
        "age": 25,
        "careerLength": 0,
        "netWorth2014": 70000,
        "yearsUntilBreakout": 0,
        "netWorth": "http://www.financialsamurai.com/the-average-net-worth-for-the-above-average-person/"
    },
    {
        "name": "Dr. Dre",
        "career": "Musician",
        "birthYear": 1965,
        "careerStart": 1984,
        "usBreakout": 1988,
        "age": 49,
        "careerLength": 30,
        "netWorth2014": 800000000,
        "yearsUntilBreakout": 4,
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/richest-rappers/dr-dre-net-worth/"
    },
    {
        "name": "Jim Buckmaster",
        "career": "Programmer",
        "knownFrom": "Craigslist",
        "birthYear": 1962,
        "careerStart": 1995,
        "usBreakout": 2000,
        "age": 52,
        "careerLength": 19,
        "netWorth2014": 40000000,
        "yearsUntilBreakout": 5,
        "bio": "http://en.wikipedia.org/wiki/Jim_Buckmaster",
        "netWorth": "http://www.celebritynetworth.com/richest-businessmen/ceos/jim-buckmaster-net-worth/"
    },
    {
        "name": "David Heinemeier Hansson",
        "career": "Programmer",
        "knownFrom": "Rails",
        "birthYear": 1979,
        "careerStart": 1999,
        "usBreakout": 2005,
        "age": 35,
        "careerLength": 15,
        "netWorth2014": 30000000,
        "yearsUntilBreakout": 6,
        "bio": "http://en.wikipedia.org/wiki/David_Heinemeier_Hansson",
        "netWorth": "http://www.celebritynetworth.com/richest-businessmen/david-heinemeier-hansson-net-worth/"
    },
    {
        "name": "Linus Torvalds",
        "career": "Programmer",
        "knownFrom": "Linux",
        "birthYear": 1969,
        "careerStart": 1996,
        "usBreakout": 1999,
        "age": 45,
        "careerLength": 18,
        "netWorth2014": 150000000,
        "yearsUntilBreakout": 3,
        "bio": "http://en.wikipedia.org/wiki/Linus_Torvalds",
        "netWorth": "http://www.celebritynetworth.com/richest-businessmen/linus-torvalds-net-worth/"
    },
    {
        "name": "Gary Vaynerchuk",
        "career": "Entreprenuer",
        "knownFrom": "Wine Library TV",
        "birthYear": 1975,
        "careerStart": 1997,
        "usBreakout": 2007,
        "age": 39,
        "careerLength": 17,
        "netWorth2014": 10000000,
        "yearsUntilBreakout": 10,
        "bio": "http://en.wikipedia.org/wiki/Gary_Vaynerchuk",
        "netWorth": "http://www.celebritynetworth.com/richest-businessmen/gary-vaynerchuk-net-worth/"
    },
    {
        "name": "Adam Levine",
        "career": "Musician",
        "knownFrom": "Maroon 5",
        "birthYear": 1979,
        "careerStart": 1994,
        "usBreakout": 2006,
        "age": 35,
        "careerLength": 20,
        "netWorth2014": 50000000,
        "yearsUntilBreakout": 12,
        "bio": "http://en.wikipedia.org/wiki/Adam_Levine",
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/rock-stars/adam-levine-net-worth/"
    },
    {
        "name": "Blake Shelton",
        "career": "Musician",
        "birthYear": 1976,
        "careerStart": 2001,
        "usBreakout": 2001,
        "age": 38,
        "careerLength": 13,
        "netWorth2014": 30000000,
        "yearsUntilBreakout": 0,
        "bio": "http://en.wikipedia.org/wiki/Blake_Shelton",
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/singers/blake-shelton-net-worth/"
    },
    {
        "name": "Donald Trump",
        "career": "Entreprenuer",
        "birthYear": 1946,
        "careerStart": 1962,
        "usBreakout": 1965,
        "age": 68,
        "careerLength": 52,
        "netWorth2014": 3900000000,
        "yearsUntilBreakout": 3,
        "bio": "http://en.wikipedia.org/wiki/Donald_Trump",
        "netWorth": "http://www.celebritynetworth.com/richest-businessmen/richest-billionaires/donald-trump-net-worth/"
    },
    {
        "name": "Mark Zuckerberg",
        "career": "Entreprenuer",
        "knownFrom": "Facebook",
        "birthYear": 1984,
        "careerStart": 2004,
        "usBreakout": 2007,
        "age": 30,
        "careerLength": 10,
        "netWorth2014": 30000000000,
        "yearsUntilBreakout": 3,
        "bio": "http://en.wikipedia.org/wiki/Mark_Zuckerberg",
        "netWorth": "http://www.celebritynetworth.com/richest-businessmen/ceos/mark-zuckerberg-net-worth/"
    },
    {
        "name": "Bill Gates",
        "career": "Entreprenuer",
        "knownFrom": "Microsoft",
        "birthYear": 1955,
        "careerStart": 1974,
        "usBreakout": 1980,
        "age": 59,
        "careerLength": 40,
        "netWorth2014": 76000000000,
        "yearsUntilBreakout": 6,
        "bio": "http://en.wikipedia.org/wiki/Bill_Gates",
        "netWorth": "http://www.celebritynetworth.com/richest-businessmen/richest-billionaires/bill-gates-net-worth/"
    },
    {
        "name": "Steve Wozniak",
        "career": "Programmer",
        "knownFrom": "Apple",
        "birthYear": 1950,
        "careerStart": 1972,
        "usBreakout": 1984,
        "age": 64,
        "careerLength": 42,
        "netWorth2014": 100000000,
        "yearsUntilBreakout": 12,
        "bio": "http://en.wikipedia.org/wiki/Steve_Wozniak",
        "netWorth": "http://www.celebritynetworth.com/richest-businessmen/steve-wozniak-net-worth/"
    },
    {
        "name": "Steve Jobs (2011)",
        "career": "Entreprenuer",
        "knownFrom": "Apple",
        "birthYear": 1955,
        "careerStart": 1972,
        "usBreakout": 1984,
        "age": 56,
        "careerLength": 42,
        "netWorth2014": 10200000000,
        "yearsUntilBreakout": 12,
        "bio": "http://en.wikipedia.org/wiki/Steve_jobs",
        "netWorth": "http://www.celebritynetworth.com/richest-businessmen/ceos/steve-jobs-net-worth/"
    },
    {
        "name": "Tim Cook",
        "career": "Entreprenuer",
        "knownFrom": "Apple",
        "birthYear": 1960,
        "careerStart": 1988,
        "usBreakout": 2011,
        "age": 54,
        "careerLength": 26,
        "netWorth2014": 400000000,
        "yearsUntilBreakout": 23,
        "bio": "http://en.wikipedia.org/wiki/Tim_Cook",
        "netWorth": "http://www.celebritynetworth.com/richest-businessmen/ceos/tim-cook-net-wrth/"
    },
    {
        "name": "Paul McCartney",
        "career": "Musician",
        "knownFrom": "The Beatles",
        "birthYear": 1942,
        "careerStart": 1957,
        "usBreakout": 1964,
        "age": 72,
        "careerLength": 57,
        "netWorth2014": 1100000000,
        "yearsUntilBreakout": 7,
        "bio": "http://en.wikipedia.org/wiki/Paul_McCartney",
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/rock-stars/paul-mccartney-net-worth/"
    },
    {
        "name": "Herb Alpert",
        "career": "Musician",
        "knownFrom": "Tijuana Brass",
        "birthYear": 1935,
        "careerStart": 1957,
        "usBreakout": 1964,
        "age": 79,
        "careerLength": 57,
        "netWorth2014": 850000000,
        "yearsUntilBreakout": 7,
        "bio": "http://en.wikipedia.org/wiki/Herb_Alpert",
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/singers/herb-alpert-net-worth/"
    },
    {
        "name": "Diana Krall",
        "career": "Musician",
        "birthYear": 1964,
        "careerStart": 1990,
        "usBreakout": 1996,
        "age": 50,
        "careerLength": 24,
        "netWorth2014": 18000000,
        "yearsUntilBreakout": 6,
        "bio": "http://en.wikipedia.org/wiki/Diana_Krall",
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/singers/diana-krall-net-worth/"
    },
    {
        "name": "Fiona Apple",
        "career": "Musician",
        "birthYear": 1977,
        "careerStart": 1994,
        "usBreakout": 1996,
        "age": 37,
        "careerLength": 20,
        "netWorth2014": 6000000,
        "yearsUntilBreakout": 2,
        "bio": "http://en.wikipedia.org/wiki/Fiona_Apple",
        "netWorth": "http://www.celebritynetworth.com/richest-celebrities/singers/fiona-apple-net-worth/"
    }
]
